import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./../../public/assets/style/customStyle.scss"
import HeaderNavbar from "./header/header";
import Footer from "./footer/footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <html>
      <body>
        <HeaderNavbar />
        {children}
        <Footer />
      </body>
    </html>


  );
}
