import { Inter } from "next/font/google";
import "./globals.css";
import "../assets/style/customStyle.scss"
import 'bootstrap/dist/css/bootstrap.min.css';
import HeaderNavbar from "./header/header";
import Footer from "./footer/footer";





// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <HeaderNavbar />
          {children}
        <Footer />
      </body>
    </html>


  );
}
